### ISSUE TITLE
Joining annotated metabolites with original tax info

### ISSUE THREAD

**Issue by ddomingof** [mandelbrot-project/pf_1600_datanote#2]
First of all, thanks for the superb organization of the repo, I tried to reproduce the scripts and it works like a charm.
I was thinking it would be interesting to compare the annotated metabolites against the phytochemicals in LOTUS and fill in the gaps adding the ones that are not linked to each species in LOTUS but you guys now found.

To do so, I am trying to join the [annotated metabolites](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_b0e0f70c/other/PF_full_datanote/PF_full_datanote_spectral_match_results_repond_flat.tsv) with the [metadata about the samples](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_7c3d8556/other/pf_metadata_otoled.tsv), but I cant figure it out how.

I can see some taxonomic information in the spectral match results file (`PF_full_datanote_spectral_match_results_repond_flat`). However, there are ~10,000 unique organisms, some of them not plants, so I assume this is not the original data from `pf_metadata_otoled` 

![Screenshot 2023-01-19 at 11 00 49](https://user-images.githubusercontent.com/15685795/213413031-f719b2f6-9527-414c-9ca2-5c3f98784899.png)

Thanks!

**Comment by ddomingof** [comment]
Hi guys @oolonek @Adafede, any thoughts on this?

**Comment by oolonek** [comment]
Hi ddomingof,

Thanks for getting in touch.
Great you could reproduce :) That's already a first good point.

I am not very sure to understand what you are aiming to do and what you mean by 

> "compare the annotated metabolites against the phytochemicals in LOTUS and fill in the gaps adding the ones that are not linked to each species in LOTUS but you guys now found."

However I think there might be a confusion regarding the nature of the data in the [annotated metabolites](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_b0e0f70c/other/PF_full_datanote/PF_full_datanote_spectral_match_results_repond_flat.tsv) and in the [metadata about the samples](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_7c3d8556/other/pf_metadata_otoled.tsv) tables. It is true that the headers might not have the best names in the [annotated metabolites](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_b0e0f70c/other/PF_full_datanote/PF_full_datanote_spectral_match_results_repond_flat.tsv) and that this might have confused you. I will explain in more detail hereafter.

This [annotated metabolites](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_b0e0f70c/other/PF_full_datanote/PF_full_datanote_spectral_match_results_repond_flat.tsv) table corresponds to the annotation results obtained on the 1600 extracts. For this we used a taxonomically informed metabolite annotation process (detailed here https://doi.org/10.3389/fpls.2019.01329). 
For each annotation we returned the top1 hit so there is usually only one annotation candidate per `feature_id`. However, sometimes, when the annotation are coming from a MS1 match there is no spectral score to discriminate equivalently ranked annotations their can be several (e.g. feature_id 1 has 4 MS1 annotations.)

Now regarding the columns. For each candidate annotation we have a set of columns describing the chemical (e.g. the chemical formula, the InChIKey, the exact mass etc.) They are usually prefixed by `structure_`. 
Then we have information regarding their biological occurrence of these structures. They are usually prefixed by `organism_`. These information come from LOTUS (see here for details https://doi.org/10.7554/eLife.70780). For example in your screenshot you can read that for row 3 `organism_name` = Streptomyces. This does not means that we annotated a spectra found to be present in an extract belonging to a Streptomyces. It means that this spectra has been annotated by a candidate structure which was previously found to be present in a Streptomyces. I guess that here is what has confused you.

The following columns will make this clearer. They are prefixed `matched_` and cover several taxa levels (e.g. `matched_domain`, `matched_family` , `matched_species` etc.). If you take again row 3 in your example you will see that you have only `NaN` for this row under the `matched_` series of columns. This is because indeed we have only extracts coming from plants, as you can see in the [metadata about the samples](https://massive.ucsd.edu/ProteoSAFe/DownloadResultFile?file=f.MSV000087728/updates/2022-04-28_pmallard_7c3d8556/other/pf_metadata_otoled.tsv) table.

However if you take feature id 1 for example. The four candidate annotations for this feature have a `organism_name` column with value "Paeonia suffruticosa" and also a `matched_species` column with value "Paeonia suffruticosa" thus indicating that this spectral feature has 4 candidate annotations corresponding to structures which have previously been found in the exact same species (hence the higher `score_taxo` value)

Let us know if this clarifies things on your side and if you have further questions.

**Comment by ddomingof** [comment]
Got i.Thanks!
So basically, I can rely on `matched_species` to find the taxonomy of the extract of the features and matched structures in that file right? Following your example, feature 1 is coming from _Paeonia suffruticosa_ since the matched structure in the database is already known to be in this plant.

Regarding my goal:
` "compare the annotated metabolites against the phytochemicals in LOTUS and fill in the gaps adding the ones that are not linked to each species in LOTUS but you guys now found."
`
I thought it would be useful to bring back the information of the phytochemicals found in each individual extract back to LOTUS, but now it is clear that LOTUS is already used.

Thanks again!
